<x-main>
    <div class="content">
        <h1><acronym title="Open Shortest Path First">OSPF</acronym> main features</h1>
        <table class="table_red">
            <th class="table_red_hd" colspan="2">Attributes</th>
            <tr>
                <td><strong>Type</strong></td>
                <td>Link-State</td>
            </tr>
            <tr>
                <td><strong>Metric</strong></td>
                <td>Cost (Bandwidth)</td>
            </tr>
            <tr>
                <td><strong>Protocols</strong></td>
                <td>IPv4, IPv6</td>
            </tr>
            <tr>
                <td><strong>Administrative Distance</strong></td>
                <td>110</td>
            </tr>
            <tr>
                <td><strong>Transport</strong></td>
                <td>IP/89</td>
            </tr>
            <tr>
                <td><strong>Authentication</strong></td>
                <td>Plaintext, MD5</td>
            </tr>
            <tr>
                <td><strong>AIISPF Address</strong></td>
                <td>224.0.0.5</td>
            </tr>
            <tr>
                <td><strong>AIIDR Address</strong></td>
                <td>224.0.0.6</td>
            </tr>
            <tr>
                <td><strong>Standards</strong></td>
                <td>RFC 2380,2740</td>
            </tr>
            <tr>
                <td><strong>Algorithm</strong></td>
                <td>Dijkstra</td>
            </tr>
        </table>
        <table class="table_black">
            <th class="table_black_hd" colspan="4">Protocol Data Unit (PDU)</th>
            <tr>
                <td style="width:100px;">8</td>
                <td style="width:100px;">16</td>
                <td style="width:100px;">24</td>
                <td style="width:100px;">32</td>
            </tr>
            <tr>
                <td>Version</td>
                <td>Type</td>
                <td colspan="2">Length</td>
            </tr>
            <tr>
                <td colspan="4">Router ID</td>
            </tr>
            <tr>
                <td colspan="4">Area ID</td>
            </tr>
            <tr>
                <td colspan="2">Checksum</td>
                <td>Instance ID</td>
                <td>Reserved</td>
            </tr>
            <tr>
                <td colspan="4">Data</td>
            </tr>
        </table>
        <!-- 	DEFAULT TALBE FORMATING	*************************************************
        <table class="table table-bordered">
        <th colspan="2">Router Types</th>
            <tr>
                <td><strong></strong></td>
                <td></td>
            </tr>
            <tr>
                <td><strong></strong></td>
                <td></td>
            </tr>
            <tr>
                <td><strong></strong></td>
                <td></td>
            </tr>
            <tr>
                <td><strong></strong></td>
                <td></td>
            </tr>

        </table> *************************************************************************** -->

        <h1>Router Types</h1>
        <ul>
            <li><strong>Internal Router - </strong>All interfaces reside within the same area</li>
            <li><strong>Backbone Router - </strong>A router with an interface in area 0 (the backbone)</li>
            <li><strong>Area Border Router (ABR) - </strong>Connects two or more areas</li>
            <li><strong>AS Boundary Router (ASBR) - </strong>Connects to additional routing domains; backbone</li>
        </ul>
        <h1>Area Types</h1>
        <ul>
            <li><strong>Standard Area - </strong>Default OSPF area type</li>
            <li><strong>Stub Area - </strong>External link (type 5) LSAs are replaced with a default route</li>
            <li><strong>Totally Stubby Area - </strong>Type 3,4 and 6 LSAs are replaced with a default route</li>
            <li><strong>Not So Stubby Area (NSSA) - </strong> A stub area containing an ASBR; type 5 LSAs are converted
                to type 7 within the area
            </li>
            <!--<li><strong></strong></li> -->
        </ul>

        <h1>Link State Advertisements</h1>
        <ul>
            <li><strong>Router Link (Type 1):</strong> Lists neighboring routers and the cost to each; flooded within an
                area.
            </li>
            <li><strong>Network Link (Type 2):</strong> Generated by a DR; lists all routers on an adjacent segment;
                flooded within an area.
            </li>
            <li><strong>Network Summary (Type 3):</strong> Generated by an ABR and advertised among areas.</li>
            <li><strong>ASBR Summary (Type 4):</strong> Injected by an ABR into the backbone to advertise the presence
                of an ASBR within an area.
            </li>
            <li><strong>External Link (Type 5):</strong> Generated by an ASBR and flooded throughout the AS to advertise
                a route external to OSPF.
            </li>
            <li><strong>NSSA External Link (Type 7):</strong> Generated by an ASBR in a not-so-stubby area; converted
                into a type 5 LSA by the ABR when leaving the area.
            </li>
        </ul>
        <h1>Adjacency States</h1>
        <ol>
            <li><b>Down: </b>No hello packets have been received from this neighbor yet.</li>
            <li><b>Attempt: </b>Router sends unicast hello packets withing dead interfal.</li>
            <li><b>Init: </b>Router has received a hello packet where its own router ID is not included.</li>
            <li><b>2-Way: </b>Bi-directional communication has started, both routers have received hello packages with
                their own router ID included in it. (Designated Router)DR/(Backup Designated Router)BDR Election takes
                place
            </li>
            <li><b>Exstart: </b>In this state, the routers and their DR and BDR establish a master-slave relationship
                and choose the initial sequence number for adjacency formation; higher router ID becomes the master.
            </li>
            <li><b>Exchange: </b>OSPF routers exchange database descriptor (DBD) packets.</li>
            <li><b>Loading: </b>Routers send link-state request packets; link-state update(LSU)/link-state request(LSR).
            </li>
            <li><b>Full: </b>Fully adjacent; link-state acknowledge(LSA) are exchanged. Database descriptors(DBD) are
                fully synchronized.
            </li>
        </ol>
        <h1>DR/BDR Election</h1>
        <ul style="list-style-type:square; padding-left:15px;">
            <li>The DR serves as a common point for all adjacencies on a multiaccess segment.</li>
            <li>The BDR also maintains adjacencies with all routers in case the DR fails.</li>
            <li>Election does not occur on point-topoint or multipoint links.</li>
            <li>Default priority (0-255) is 1; highest priority wins; 0 cannot be elected.</li>
            <li>DR preemption will not occur unless the current DR is reset.</li>
        </ul>
        <h1>Virtual Links</h1>
        <ul style="list-style-type:square;padding-left:15px;">
            <li>Tunnel formed to join two areas across an intermediate</li>
            <li>Both end routers must share a common area</li>
            <li>At leaset one end must reside in area 0</li>
            <li>Cannot traverse stub areas</li>
        </ul>
        <h1>How to configure OSPF</h1>
        <h4>How to configure routing protocol and directly connected networks.</h4>
        <p class="well well-sm code">
            <b>router#</b> config t
            <br/><b>router(config)#</b> router ospf < <em>process number</em> >
            <br/><b>router(config-router)#</b> network < <em>ip address</em> > < <em>wildcard subnetmask</em> > area <
            <em>area number</em> >
            <br/><b>router(config-router)#</b> end
            <br/><b>router#</b> wr
        </p>

        <h4>How to configure interfaces</h4>
        <p class="well well-sm code">
            <b>router></b> enable
            <br/><b>router#</b> config t
            <br/><b>router(config)#</b> interface < <em>interface</em> >
            <br/><b>router(config-if)#</b> ip address < <em>ip addr.</em> > < <em>subnetmask</em> >
            <br/><b>router(config-if)#</b> no shutdown
        </p>

        <h4>Additional configuration commands</h4>
        <p class="well well-sm code">
            <b>router(config-router)#</b> redistribute static subnets
            <br/><b>router(config-router)#</b> ip ospf authentication message-digest
            <br/><b>router(config-router)#</b> ip ospf message-digest-key 1 md5 < <em>keyname</em> >
            <br/><b>router(config-router)#</b> ip ospf priority < <em>number</em> >
        </p>

        <h4>Troubleshooting</h4>
        <p class="well well-sm code">
            <b>router#</b> show ip { route | protocols }
            <br/><b>router#</b> show ip ospf interface
            <br/><b>router#</b> show ip ospf neightbor
            <br/><b>router#</b> show ip ospf border-routers
            <br/><b>router#</b> show ip ospf virtual-links
            <br/><b>router#</b> debug ip ospf [...]
        </p>
        <p>Source <a href="http://packetlife.net">PacketLife</a></p>
    </div>
</x-main>>
